Revert "just --unstable"
This reverts commit b6673496d62b051b3994fa6e29d4595745f554a5.

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -39,7 +39,7 @@ jobs:
           just --version
           echo "=== just dump test ==="
           cd test/fixtures
-          just --unstable --dump --dump-format json || echo "just dump failed with exit code $?"
+          just --dump --dump-format json || echo "just dump failed with exit code $?"
           echo "=== rake tasks test ==="
           rake --all --tasks || echo "rake tasks failed with exit code $?"
 
